Added Littletable to bigtable emulators
zrosenbauer/awesome-bigtable pull request #4
Opened 2019-02-05 18:18 UTC by steveniemitz

2019-02-11 16:03 UTC, mbrukman requested changes

2019-02-11 16:03 UTC, mbrukman commented on README.md
> +- [Littletable](https://github.com/steveniemitz/littletable) - In-memory JVM-based emulator for Bigtable.
s/Littletable/LittleTable/ since I think that's how you capitalize it in the docs? Otherwise, LGTM. Thanks!

2019-03-18 05:44 UTC, zrosenbauer commented
@steveniemitz you want to update your PR so we can get this in?

2019-03-18 19:56 UTC, steveniemitz commented
oh thanks for the ping, I had totally forgotten about this :)

2019-03-18 20:27 UTC, mbrukman approved these changes
LGTM

2019-03-18 20:27 UTC, merged

2019-03-18 20:27 UTC, mbrukman commented
Thanks for the PR, @steveniemitz!